program marksheet
implicit none
write(*,*) '                                                                                             '
write(*,*) '                                             ___/\___                                           '
write(*,*) '                                             \ /  \ /                                           '
write(*,*) '                                              \ TU \                                            '
write(*,*) '                                             /_\__/_\                                           '
write(*,*) '                                                \/                                              '
write(*,*) '                                                                                                '
write(*,*) '                                       Tribhuvan University                                     '
write(*,*) '                                 Institute of science and Technology                            '
write(*,*) '                                           Office of Dean                                       '
write(*,*) '                                                                                                '
write(*,*) '                                                                                                '
write(*,*) '                                    Semester Examination 2080                                   '
write(*,*) '                                                                                             '
write(*,*) 'Name of Student: PAWAN JOSHI                                    Exam Roll No: PHY 3866/066      '
write(*,*) 'Level: Master of Science in Physics                             T.U.Regd No: 5-2-327-1655-2016  '
write(*,*) 'Campus: University Campus, Kirtipur                             Semester: Third                 '
write(*,*) '                                                                                                '
write(*,*) '                                            Grade Sheet                                         '
write(*,*) '                                                                                                '
write(*,*) '_________________________________________________________________   ____________________________'
write(*,*) '|        |                    |       |    1st Term     |      2nd Term     |  Final Term      |'
write(*,*) '|        |                    |       |_________________|___________________|__________________|'
write(*,*) '|Code No.|    Course Title    |Cr.Hrs.|Grade Point|Grade|Grade Point|  Grade|Grade Point|Grade |'
write(*,*) '|________|____________________|_______|___________|_____|___________|_______|___________|______|'
write(*,*) '|PHY601  |Quantum Field Theory|   3   |    4.0    |  A  |    4.0    |   A   |    4.0    |  A   |'
write(*,*) '|________|____________________|_______|___________|_____|___________|_______|___________|______|'
write(*,*) '|PHY602  |Electrodynamics II  |   3   |    4.0    |  A  |    4.0    |   A   |    4.0    |  A   |'
write(*,*) '|________|____________________|_______|___________|_____|___________|_______|___________|______|'
write(*,*) '|PHY603  |Math Physics        |   3   |    4.0    |  A  |    4.0    |   A   |    4.0    |  A   |'
write(*,*) '|________|____________________|_______|___________|_____|___________|_______|___________|______|'
write(*,*) '|PHY604  |Computational Lab   |   4   |    4.0    |  A  |    4.0    |   A   |    4.0    |  A   |'
write(*,*) '|________|____________________|_______|___________|_____|___________|_______|___________|______|'
write(*,*) '|PHY605  |Term Paper (III)    |   2   |    4.0    |  A  |    4.0    |   A   |    4.0    |  A   |'
write(*,*) '|________|____________________|_______|___________|_____|___________|_______|___________|______|'
write(*,*) '|PHY611  |Adv. Solid State PHY|   2   |    4.0    |  A  |    4.0    |   A   |    4.0    |  A   |'
write(*,*) '|________|____________________|_______|___________|_____|___________|_______|___________|______|'
write(*,*) '                                                                                                '
write(*,*) '                                                                                ____________    '
write(*,*) '                                                                               |SGPA: 4.0   |   '
write(*,*) '                                                                               |____________|   '
write(*,*) '                                                                                                '
write(*,*) '                                                                                                '
write(*,*) ' Verified by:                                                                 ________________  '
write(*,*) ' Date: 22 Novemember 2023                                                      Assistant Dean   '

end program marksheet
